export const primaryTables = [
  ['user', ['id']],
  ['account', ['id']],
  ['session', ['id']],
  ['verification', ['id']],
  ['rate_limit', ['id']],
  ['sites', ['id']],
  ['environments', ['id']],
  ['account_onboarding', ['owner_id']],
  ['billing_customers', ['customer_id']],
  ['billing_checkouts', ['owner_id']],
  ['billing_webhook_events', ['id']],
  ['billing_usage', ['owner_id', 'period_start', 'site_id']],
  ['free_usage', ['owner_id', 'period_start', 'site_id']],
  ['billing_organization_usage', ['organization_id', 'owner_id', 'period_start', 'site_id']],
  ['billing_outbox', ['id']],
  ['abuse_sources', ['environment_id', 'source']],
  ['abuse_environment', ['environment_id']],
  ['abuse_daily', ['environment_id', 'day', 'reason']],
  ['conversion_goals', ['id']],
  ['error_resolutions', ['environment_id', 'fingerprint']],
  ['overview_annotations', ['id']],
  ['user_suspensions', ['user_id']],
  ['site_suspensions', ['site_id']],
  ['admin_audit_log', ['id']],
] as const;

export const analyticsTables = [
  ['events', ['site_id', 'id', 'day']],
  ['activity_events', ['environment_id', 'id', 'received_at']],
  ['daily_stats', ['site_id', 'day', 'dimension', 'value']],
  ['daily_visitors', ['site_id', 'day', 'visitor']],
  ['diagnostic_events', ['environment_id', 'id', 'received_at']],
  ['goal_conversions', ['goal_id', 'event_id', 'day']],
  ['analytics_imports', ['id']],
  ['imported_daily_stats', ['environment_id', 'day']],
  ['imported_breakdowns', ['environment_id', 'day', 'dimension', 'value']],
] as const;

export const targetTables = { primary: primaryTables, analytics: analyticsTables };
