/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppAccountRouteImport } from './routes/_app.account'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppSigninRouteImport } from './routes/_app.signin'
import { Route as AppSignupRouteImport } from './routes/_app.signup'
import { Route as AppSiteSiteIdRouteImport } from './routes/_app.site.$siteId'
import { Route as AppSiteSiteIdEnvironmentIdRouteImport } from './routes/_app.site.$siteId.$environmentId'
import { Route as AppSiteSiteIdEnvironmentIdPageRouteImport } from './routes/_app.site.$siteId.$environmentId.$page'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSigninRoute = AppSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AppRoute,
} as any)
const AppSignupRoute = AppSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AppRoute,
} as any)
const AppSiteSiteIdRoute = AppSiteSiteIdRouteImport.update({
  id: '/site/$siteId',
  path: '/site/$siteId',
  getParentRoute: () => AppRoute,
} as any)
const AppSiteSiteIdEnvironmentIdRoute =
  AppSiteSiteIdEnvironmentIdRouteImport.update({
    id: '/$environmentId',
    path: '/$environmentId',
    getParentRoute: () => AppSiteSiteIdRoute,
  } as any)
const AppSiteSiteIdEnvironmentIdPageRoute =
  AppSiteSiteIdEnvironmentIdPageRouteImport.update({
    id: '/$page',
    path: '/$page',
    getParentRoute: () => AppSiteSiteIdEnvironmentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/account': typeof AppAccountRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/signin': typeof AppSigninRoute
  '/signup': typeof AppSignupRoute
  '/site/$siteId': typeof AppSiteSiteIdRouteWithChildren
  '/site/$siteId/$environmentId': typeof AppSiteSiteIdEnvironmentIdRouteWithChildren
  '/site/$siteId/$environmentId/$page': typeof AppSiteSiteIdEnvironmentIdPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/account': typeof AppAccountRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/signin': typeof AppSigninRoute
  '/signup': typeof AppSignupRoute
  '/site/$siteId': typeof AppSiteSiteIdRouteWithChildren
  '/site/$siteId/$environmentId': typeof AppSiteSiteIdEnvironmentIdRouteWithChildren
  '/site/$siteId/$environmentId/$page': typeof AppSiteSiteIdEnvironmentIdPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/signin': typeof AppSigninRoute
  '/_app/signup': typeof AppSignupRoute
  '/_app/site/$siteId': typeof AppSiteSiteIdRouteWithChildren
  '/_app/site/$siteId/$environmentId': typeof AppSiteSiteIdEnvironmentIdRouteWithChildren
  '/_app/site/$siteId/$environmentId/$page': typeof AppSiteSiteIdEnvironmentIdPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/site/$siteId'
    | '/site/$siteId/$environmentId'
    | '/site/$siteId/$environmentId/$page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/site/$siteId'
    | '/site/$siteId/$environmentId'
    | '/site/$siteId/$environmentId/$page'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/_app/account'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/signin'
    | '/_app/signup'
    | '/_app/site/$siteId'
    | '/_app/site/$siteId/$environmentId'
    | '/_app/site/$siteId/$environmentId/$page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signin': {
      id: '/_app/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AppSigninRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signup': {
      id: '/_app/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AppSignupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/site/$siteId': {
      id: '/_app/site/$siteId'
      path: '/site/$siteId'
      fullPath: '/site/$siteId'
      preLoaderRoute: typeof AppSiteSiteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/site/$siteId/$environmentId': {
      id: '/_app/site/$siteId/$environmentId'
      path: '/$environmentId'
      fullPath: '/site/$siteId/$environmentId'
      preLoaderRoute: typeof AppSiteSiteIdEnvironmentIdRouteImport
      parentRoute: typeof AppSiteSiteIdRoute
    }
    '/_app/site/$siteId/$environmentId/$page': {
      id: '/_app/site/$siteId/$environmentId/$page'
      path: '/$page'
      fullPath: '/site/$siteId/$environmentId/$page'
      preLoaderRoute: typeof AppSiteSiteIdEnvironmentIdPageRouteImport
      parentRoute: typeof AppSiteSiteIdEnvironmentIdRoute
    }
  }
}

interface AppSiteSiteIdEnvironmentIdRouteChildren {
  AppSiteSiteIdEnvironmentIdPageRoute: typeof AppSiteSiteIdEnvironmentIdPageRoute
}

const AppSiteSiteIdEnvironmentIdRouteChildren: AppSiteSiteIdEnvironmentIdRouteChildren =
  {
    AppSiteSiteIdEnvironmentIdPageRoute: AppSiteSiteIdEnvironmentIdPageRoute,
  }

const AppSiteSiteIdEnvironmentIdRouteWithChildren =
  AppSiteSiteIdEnvironmentIdRoute._addFileChildren(
    AppSiteSiteIdEnvironmentIdRouteChildren,
  )

interface AppSiteSiteIdRouteChildren {
  AppSiteSiteIdEnvironmentIdRoute: typeof AppSiteSiteIdEnvironmentIdRouteWithChildren
}

const AppSiteSiteIdRouteChildren: AppSiteSiteIdRouteChildren = {
  AppSiteSiteIdEnvironmentIdRoute: AppSiteSiteIdEnvironmentIdRouteWithChildren,
}

const AppSiteSiteIdRouteWithChildren = AppSiteSiteIdRoute._addFileChildren(
  AppSiteSiteIdRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAdminRoute: typeof AppAdminRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSigninRoute: typeof AppSigninRoute
  AppSignupRoute: typeof AppSignupRoute
  AppSiteSiteIdRoute: typeof AppSiteSiteIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAdminRoute: AppAdminRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSigninRoute: AppSigninRoute,
  AppSignupRoute: AppSignupRoute,
  AppSiteSiteIdRoute: AppSiteSiteIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
